- name: 检查服务器是否存在
  ansible.builtin.stat:
    path: "{{ workspace }}/users-token/{{ username }}.token"
  register: server_token_file
  
- name: 生成token
  when: server_token_file.stat.exists == false
  ansible.builtin.shell:
    cmd: |
      mkdir -p users-token
      bin/pulsar tokens create --secret-key {{ secret_key }} --subject {{ username }} > users-token/{{ username }}.token
    chdir: "{{ workspace }}"

- name: 下载token111
  ansible.builtin.fetch:
    src: "{{ workspace }}/users-token/{{ username }}.token"
    dest: "{{ playbook_dir }}/users-token/{{ username }}.token"
    flat: true