- name: 检查systemd文件是否存在
  ansible.builtin.stat:
    path: /etc/systemd/system/pulsar.service
  register: systemd_file
- name: 生成systemd
  ansible.builtin.template:
    src: systemd.j2
    dest: /etc/systemd/system/pulsar.service
    owner: root
    group: root
    mode: 0644
  when: systemd_file.stat.exists == false
- name: 重启pulsar
  ansible.builtin.service:
    name: pulsar
    state: restarted
    daemon_reload: yes